# Generated by Django 3.2.5 on 2021-08-24 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points_purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='points_purchase',
            name='num',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
                ('purchase_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.points_purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
