# Generated by Django 3.2.5 on 2021-08-26 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyActivityPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_num", models.IntegerField()),
                ("attendance", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "weekly_studies",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
