# Generated by Django 3.2.5 on 2021-09-18 23:36

import adminpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0003_auto_20210829_0535"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressPointsFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("1", "1차 진도율"),
                            ("2", "2차 진도율"),
                            ("3", "3차 진도율"),
                            ("final", "최종 진도율"),
                            ("completion", "종료 시점 진도율 (수료증)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=adminpage.models.make_file_path_progress
                    ),
                ),
            ],
        ),
    ]
