# Generated by Django 3.2.6 on 2021-09-23 08:55

import adminpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_rename_title_progresspointsfile_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroupAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('csv_file', models.FileField(upload_to=adminpage.models.make_file_path_groupinfo)),
            ],
        ),
    ]
