# Generated by Django 3.2.5 on 2021-09-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_info_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='individual',
            field=models.BooleanField(blank=True, default=False, help_text='파이썬 코스를 개인 단위로 수강하고자 하시는 분들은 체크해주세요! (데이터 사이언스 코스의 경우 스터디 활동이 필수이며, 웹 퍼블리싱 코스는 개인 단위로 이루어집니다.)', null=True),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='purchase',
            field=models.BooleanField(default=False, help_text='BruteForce 프로그램에 참여하기 위해서는 멤버십 구매가 필요합니다. 구매를 완료하셨다면 체크해주세요!'),
        ),
    ]
