# Generated by Django 3.2.5 on 2021-09-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210826_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklystudies',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
