# Generated by Django 3.2.6 on 2021-09-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_weeklystudies_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='open_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
