# Generated by Django 3.2.6 on 2021-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_material_open_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="open_week",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
