# Generated by Django 3.2.6 on 2021-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_material_open_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="num",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
